### ISSUE TITLE
How to specify a destination directory?

### ISSUE THREAD

**Issue by rocchidavide** [jarun/imgp#11]
Is it possible to specify a destination directory for the output?

**Comment by jarun** [comment]
If you mean output directory, no. `imgp` adds the _IMGP extension. The main reason it wasn't added is - we wanted to avoid locking files for exclusive writes. Keeps things simpler. Otherwise files from two different sources with the same name would have enforced it.

**Comment by jarun** [comment]
Moving `*_IMGP*` files to another directory is the only solution in this case.

**Comment by rocchidavide** [comment]
Ok, thank you
