### ISSUE TITLE
Homebrew tap

### ISSUE THREAD

**Issue by zmwangx** [jarun/imgp#14]
Here's the formula file:

https://gist.githubusercontent.com/anonymous/9afa5f317d3db9f1473f5cfe106eb55e/raw/afc707cf9c7f774ba2387646390b6a78a8329db7/imgp.rb

As usual, create a repository `jarun/homebrew-imgp`, place `imgp.rb` in there, and tada. The installation command is

```
brew install jarun/imgp/imgp
```

Of course you can use a central repository `jarun/homebrew-blah` to host multiple formulae if you'd like to. In that case, `brew install jarun/blah/imgp`.

Note that I'm assuming an upstream wheel of Pillow here, which means it probably won't work with Linuxbrew.

**Comment by jarun** [comment]
Thank you so much! I'll have homebrew-imgp. It'll be the only one of it's type once nnn is accepted. No issues with Linuxbrew, already several way to install on Linux.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/imgp/commit/4f2a198a8e26e7fd8b05dc4fdf062d3a0346fe72.

Once again, thanks a ton for helping out!

**Comment by zmwangx** [comment]
No problem.
