### ISSUE TITLE
Some images color saturation is reduced after running the image through imgp.

### ISSUE THREAD

**Issue by jgoslow** [jarun/imgp#15]
I was using imgp to resize a bunch of product images, and found that one or two lost it's luster (i.e. the color saturation was reduced).  I've included an example of the original and new image - curious if there's any improvement to the tool that could solve for this - or if there was a setting I missed.

![140174_campaign copy_imgp](https://user-images.githubusercontent.com/8441994/27765321-1f6e3d6c-5e63-11e7-86c4-51b4f66b5b64.jpg)
![140174_campaign copy](https://user-images.githubusercontent.com/8441994/27765322-1f6e8fd8-5e63-11e7-861f-086e59ee05c9.jpg)

**Comment by jarun** [comment]
RGB and HSL are two representations of the same image. If you want to resize an image to 50%, the original colors are not retained. It gets smaller by a factor of two in each dimension, and the color of each pixel will be the average of four pixels from the original. Depending on the colors in the image, you may sense loss of glossiness.

Your original image is 2100x3000, 3.21MB. Converted to 1000x1429, 124KB.

There is the `quality` option which can take care of this to some extent:

`image_fullsize.save(filepath+name_fullsize, quality=95)`

Default is 75. However, the last time I tried it several images became larger. ;) I can expose it though. Do you think it's a good idea?

**Comment by jarun** [comment]
The quality option doesn't affect PNG images, is default 75 for JPEG and 80 for WebP etc. (note: we don't support WebP yet). I believe the reason I omitted this in the first place was it's not uniform across the formats. That still holds true.

Closing the issue.

**Comment by jarun** [comment]
Additional note: we need uniform supported functionality because imgp is optimized to be a batch utility. If things that don't work across the board start getting added, we would start receiving and keep spending time on issues those are not our problems.

**Comment by ananyajana** [comment]
Quality is supported for JPEGs at https://github.com/jarun/imgp/commit/d4d035359f8f037932d9363afe1b55e732b4b7d4.
