### ISSUE TITLE
Some JPGs are not being recognized as JPGs

### ISSUE THREAD

**Issue by tribut** [jarun/imgp#21]
When I throw a JPG from my camera at imgp, it says it is not a JPG (but it is):

~~~~
$ ~/dev/imgp/imgp -x 1920x1920 -p -z P1010670.JPG 
P1010670.JPG: not JPEG or PNG image
$ file P1010670.JPG 
P1010670.JPG: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=13, manufacturer=Panasonic, model=DMC-GX80, orientation=upper-left, xresolution=190, yresolution=198, resolutionunit=2, software=Ver.1.2  , datetime=2017:10:31 12:59:19], baseline, precision 8, 4592x3448, frames 3
~~~~

Here is an image so you can try it for yourself: https://wolke.tribut.de/s/6x3w2sAAy3DBSmZ

**Comment by jarun** [comment]
The file is actually an [MPO file](https://en.wikipedia.org/wiki/JPEG#JPEG_Multi-Picture_Format)

However, it gets converted so I guess we can add it, though undocumented.

- I am not sure of any side effects. Maybe the first available image is only converted to JPEG.
- Pillow provides only [read-only MPO support](http://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#mpo).
