### ISSUE TITLE
Add in the ability to modify DPI

### ISSUE THREAD

**Issue by sammarder** [jarun/imgp#25]
I would really like to have the ability to modify this in an image but I am not sure how to alter the code to do so.

**Comment by jarun** [comment]
Changing DPI changes the metadata of the image and not the content. This is not in the scope of the project. However, you can write a small script in PIL to do the same. Here's some [sample code](https://stackoverflow.com/questions/28344258/with-pythons-pil-how-to-set-dpi-before-loading-an-image).
