### ISSUE TITLE
Picture example of the adaptive mode

### ISSUE THREAD

**Issue by liwt31** [jarun/imgp#31]
The adaptive mode is a cool feature and is documented well in the README file. But as they say, a picture is worth thousands of words. I think it might be clearer for readers if there are corresponding picture examples to recognize what will happen. Just a suggestion, might be a "Good First Issue".

**Comment by jarun** [comment]
Could you kindly record an asciinema session and contribute this feature?

**Comment by liwt31** [comment]
Thanks for the invitation, but I'm not really good at these "presentation" things. Feel free to close this issue if there's no proper candidate. Very good project BTW!

**Comment by jarun** [comment]
Neither am I! So I put it down in words the best I could. Closing the defect.
