### ISSUE TITLE
Process images less than 350KB

### ISSUE THREAD

**Issue by Zhangxuri** [jarun/imgp#32]
how to resize an image to at most 350kb?

**Comment by jarun** [comment]
That option is not available today (max size). What's your use case?

**Comment by Zhangxuri** [comment]
> That option is not available today (max size). What's your use case?

I use some algorithms to do image processing, and my GPU is 1080Ti. With my algorithms, if the size of the image exceeds 1MB(may be 350KB), an Out of Memory error will be thrown. So I just want to know how to let all my pictures less than 1MB.

**Comment by jarun** [comment]
Please raise a PR following the current implementation of min size.

**Comment by Zhangxuri** [comment]
> Please raise a PR following the current implementation of min size.

Sorry, I understand this ‘-s’ parameter incorrectly. I thought it would handle all the images, large image compression, small image enlargement, so that all image sizes are larger than a '-s' value.Now I need to compress all the images larger than 1MB to less than 1MB. Is there any way to achieve this?

**Comment by jarun** [comment]
Use `-s 1048576`.
