### ISSUE TITLE
Specify output directory?

### ISSUE THREAD

**Issue by shinebayar-g** [jarun/imgp#35]
Hi, thanks for the tool. Is it possible to specify output directory?

**Comment by jarun** [comment]
Please raise a PR.

Just ensure the output directory is not a subdir of the any of the source directories (including default current dir) being processed.

**Comment by jarun** [comment]
There's another problem. Say we are passing an output fir which does not overlap with any of the source dirs. But what if 2 source dirs have a file with the same name? With multicore processing we may end up in a race condition. I would like to avoid locking reads and writes to files to save on time and processing.

In case you are having issues in collecting the processed files, the following command will move the `_IMGP` files to a destination directory:

    mv *_IMGP.* destdir
