### ISSUE TITLE
Feature Request: Rename Flag

### ISSUE THREAD

**Issue by vorpalhex** [jarun/imgp#36]
Hey, this is a great utility, thank you for writing it!

I'm using imgp to resize images for a blog, and I need to produce several different resolutions of the same image with consistent naming, eg `myimage-1080.jpg` `myimage-720.jpg` etc. 

Currently this is possible using the separate posix `rename` utility, but it would be nice to be able to change `_IMGP` to a custom string, possible with a flag such as `--rename my-text-goes-here` with imgp itself.

**Comment by Hund** [comment]
I will borrow this thread a little bit if it's okay, I'm was looking for a similar feature myself. I would also like to be able to specify the output.

I often use imgp to  create thumbnails of pictures I use for my blog. The current routine is currently:

```
$ imgp -x 360x360 example.jpg
$ mv example_IMGP.jpg thumbnails/example.jpg
```

It would be a lot easier if you could have en output flag `-o,--output`. This example would create the new resized image in the folder `thumbnails` with the same name `example.jpg`:

```
$ imgp -x 360x360 example.jpg -o thumbails/
```

Or to specify another filename

```
$ imgp -x 360x360 example.jpg -o example-thumbnail.jpg
```

It would make life a lot eaiser. :)

**Comment by jarun** [comment]
I haven't added subdirs consciously because in a batch processing mode even the subdir would be picked. And I would like to avoid an option just for the single-shot mode.

You can solve this easily by using a wrapper script which does the following:

```sh
imgp $1 do somthing
mv $1_IMGP $2 // whatever output file path you want is in $2
```

**Comment by vorpalhex** [comment]
@Hund and anyone else who might come across this issue - In order to save myself from a bunch of bash scripting, I just wrote a new image resizing utility for these cases that handles both globs and renames: https://gitlab.com/vorpalhex/responsimg/

**Comment by Hund** [comment]
> @Hund and anyone else who might come across this issue - In order to save myself from a bunch of bash scripting, I just wrote a new image resizing utility for these cases that handles both globs and renames: https://gitlab.com/vorpalhex/responsimg/

Neat! I will check it out. :)
