### ISSUE TITLE
(Feature Request) Print Total Space Saved at End of Job

### ISSUE THREAD

**Issue by rsomani95** [jarun/imgp#42]
Hi @jarun,

Thanks for this tool. It's been extremely useful and has the best compression settings w.r.t quality out of the box and is also super performant!

It would be very useful (and also showcase the tool better) if the program could print out the total amount of space saved (in MB preferably)

**Comment by jarun** [comment]
Sorry, no plans to add that. If you want it, add it within debug flag.
