### ISSUE TITLE
resolution param not work

### ISSUE THREAD

**Issue by Cha0sX** [jarun/imgp#48]
the log is here:

➜  123 imgp -x 1366x0
Source omitted. Processing current directory...

./20210725_144420.jpg
4032x3024 -> 4032x3024
1445180 bytes -> 838738 bytes

./20210725_144350.jpg
4032x3024 -> 4032x3024
1838832 bytes -> 946717 bytes

./20210725_144408.jpg
4032x3024 -> 4032x3024
1926639 bytes -> 957304 bytes

./20210725_144339.jpg
4032x3024 -> 4032x3024
2691680 bytes -> 892383 bytes

./20210725_144345.jpg
4032x3024 -> 4032x3024
6153433 bytes -> 981851 bytes

5 processed in 0.7151 seconds.
/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 12 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by jarun** [comment]
See option `-f`.
