### ISSUE TITLE
cannot convert PNG files in palette mode')

### ISSUE THREAD

**Issue by jacknion** [jarun/imgp#50]
Hi,

When i convert many files in a folder, i got error message:"cannot convert PNG files in palette mode".
I found it is because my png file need to be converted.
Can we add some function to fix it ?

Thanks.

**Comment by jarun** [comment]
Introduced in PR #30.

@yzhs do you know what the restriction is from PIL side?

**Comment by yzhs** [comment]
I have no idea, sorry. Honestly, I was fine with not losing my images.

That said, for all I know, it might just work now.

**Comment by jarun** [comment]
> it might just work now

Can any of you guys confirm? Have a backup of your image before testing.
