### ISSUE TITLE
Error -a/--adapt: ignored explicit argument 'сkx'

### ISSUE THREAD

**Issue by cawa-93** [jarun/imgp#51]
Hello. I'm trying to download images, convert PNG to JPG and make JPG progressive. But I'm getting an error and can't figure out what I'm doing wrong.
```
imgp -wraсkx 300x0 ./public/thumbnails/
```
```
imgp: error: argument -a/--adapt: ignored explicit argument 'сkx'
Error: Process completed with exit code 2.
```

**Comment by jarun** [comment]
I was able to repro it but after a few tries it went away. Try separating the options.
