### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vaygr** [jarun/imgp#54]
Most rolling distros ship Pillow 10+ now, which leaves imgp broken because of #49.

Maybe it makes sense to bump the release so it gets updated, e.g. in AUR?

**Comment by jarun** [comment]
Sure! I will try make one soon. Thanks to bringing this up.

**Comment by jarun** [comment]
Closed at commit f252e27.

**Comment by vaygr** [comment]
Excellent, thanks!
